services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"   # host:container -> Postgres écoute toujours sur 5432 dedans
    volumes:
      - wallet_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-api:
    build: .
    container_name: wallet-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"   # host:container -> Spring Boot écoute toujours sur 8080 dedans

volumes:
  wallet_pgdata:
